name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore SmartDateRangeParser/SmartDateRangeParser.sln

      - name: Build for Release
        run: dotnet build SmartDateRangeParser/SmartDateRangeParser.sln --configuration Release

      - name: Pack NuGet Package
        run: dotnet pack src/SmartDateRangeParser/SmartDateRangeParser.csproj --configuration Release -o out

      - name: Push to NuGet
        run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
