name: Build and Test SmartDateRangeParser

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [netstandard2.0, net8.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore SmartDateRangeParser/SmartDateRangeParser.sln

      - name: Build ${{ matrix.framework }}
        run: dotnet build SmartDateRangeParser/SmartDateRangeParser.sln --framework ${{ matrix.framework }} --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore SmartDateRangeParser/SmartDateRangeParser.sln

      - name: Run tests
        run: dotnet test tests/SmartDateRangeParser.Tests/SmartDateRangeParser.Tests.csproj --framework net8.0
